version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password@@aa      # root password
      MYSQL_DATABASE: backend                # initial database
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql            # persist data

volumes:
  mysql_data:
